version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python -m venv /tmp/venv
      - source /tmp/venv/bin/activate
      - pip install Flask
  build:
    commands:
      - cp -r /tmp/venv/lib/python3.8/site-packages/* .
      - zip -r deployment_package.zip lambda_function.py *
      - aws s3 cp deployment_package.zip s3://bucketforttrigger/deployment_package.zip
      - aws lambda update-function-code --function-name lambdafortrigger --s3-bucket bucketforttrigger --s3-key deployment_package.zip

