version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Use a version supported by the build environment
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover tests

artifacts:
  files: '**/*'
  discard-paths: yes

cache:
  paths:
    - '$HOME/.cache/pip'
